// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package db

import (
	"database/sql"
	"time"

	"github.com/shopspring/decimal"
)

type Event struct {
	ID          int32           `json:"id"`
	OrganizerID int32           `json:"organizer_id"`
	Name        string          `json:"name"`
	TicketQuota int32           `json:"ticket_quota"`
	Price       decimal.Decimal `json:"price"`
	CreatedAt   time.Time       `json:"created_at"`
	UpdatedAt   time.Time       `json:"updated_at"`
}

type Reservation struct {
	ID              int32          `json:"id"`
	CustomerID      int32          `json:"customer_id"`
	EventID         int32          `json:"event_id"`
	TicketsReserved int32          `json:"tickets_reserved"`
	Status          sql.NullString `json:"status"`
	CreatedAt       time.Time      `json:"created_at"`
}

type User struct {
	ID           int32     `json:"id"`
	Name         string    `json:"name"`
	Email        string    `json:"email"`
	PasswordHash string    `json:"password_hash"`
	Role         string    `json:"role"`
	CreatedAt    time.Time `json:"created_at"`
}
